export const COLOR_COUNT = 4
export const CIRCLE_LAYER_COUNT = 3
export const CIRCLE_COUNT = 10
export const CIRCLE_MIN_RADIUS = 50
export const CIRCLE_MAX_RADIUS = 120
export const CIRCLE_OPACITY_CLAMP_RADIUS = 60
export const SPIN_CIRCLE_COUNT = 15
export const SPIN_CIRCLE_MIN_RADIUS = 20
export const SPIN_CIRCLE_MAX_RADIUS = 100
export const SPIN_CIRCLE_MIN_ROTATION = (Math.PI / 180) * 5
export const SPIN_CIRCLE_MAX_ROTATION = (Math.PI / 180) * 20
